# Generated by Django 5.1.1 on 2024-11-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=15, max_digits=15)),
                ('property_type', models.CharField(max_length=20)),
                ('number_of_bedrooms', models.PositiveBigIntegerField()),
                ('square_footage', models.PositiveBigIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('property_image', models.ImageField(upload_to='realestateimg')),
                ('contact_detaild', models.CharField(max_length=100)),
            ],
        ),
    ]
