# Generated by Django 5.1.1 on 2024-11-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='property_image',
            field=models.ImageField(null=True, upload_to='realestateimg'),
        ),
    ]
